### PR TITLE
Changed admin routing

### PR DESCRIPTION
**Pull request by riker09**
Changed the way this module integrates in the Magento backend due to security changes in Magento 1.9.x.x.

It should be considered to rename some of the controllers since they introduce a rather generic namespace (index), which potentially conflicts with other third-party modules.

[EDIT]
Sorry, I branched off from master instead of develop. But I incorporated all changes from develop as well.  So it should merge nicely.
[/EDIT]

### CODE REVIEW

**Comment by avoelkl** [comment]
:+1:

**Comment by therouv** [comment]
Thanks, @riker09 !
I merged your changes and did some additional work (moved controllers to subdirectories, bugfix for "checkSystem" view).

**Comment by riker09** [comment]
Any idea when you will be releasing this in master?

**Comment by therouv** [comment]
@riker09 I released a new version 45 minutes ago :-)

**Comment by riker09** [comment]
@therouv Oh, okay then. Great news!

**Pull request merged**
